spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Seoul&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update    # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        jdbc:
          timezone: Asia/Seoul
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET}
  access-exp-ms: 1800000        # 30분 (Access Token 만료시간)
  refresh-exp-ms: 604800000     # 7일 (Refresh Token 만료시간)